### ISSUE TITLE
Featurerequest ipv6 

### ISSUE THREAD

**Issue by kpleines** [angryziber/klite#3]
Dear contributers, 
this is more a feature request than an isue. 
First thankyou for angryziber or angry ip tool. 

My question is: is it possible to show the ipv6 in dashboard or to search for it?
thx

**Comment by angryziber** [comment]
@kpleines if you are talking about Angry IP Scanner, then the correct repo is https://github.com/angryip/ipscan
And yes, IPv6 is supported there.
